#docker-config/php/local.ini

# Augmentem la memòria per si l'IA o el processament de música és pesat
memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M

# Mostrem tots els errors per poder debugar bé el TFG
error_reporting = E_ALL
display_errors = On
display_startup_errors = On

# Optimitzacions per a Laravel
date.timezone = UTC