<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Stores AI-generated audio features and a textual description for a song.
 *
 * These features are generated by the Ollama LLM (LLaMA 3.2) during the
 * FetchSongFeaturesJob background process. Each song has at most one
 * SongFeature record. The values mirror Spotify's audio features schema
 * but are AI-estimated rather than fetched from the Spotify API.
 *
 * Key features used by the recommendation engine:
 * - `valence` (0.0–1.0): Musical positivity/happiness
 * - `energy` (0.0–1.0): Intensity and activity level
 * - `description`: Natural-language description used for vector embedding
 *
 * @property int         $id
 * @property int         $song_id           Foreign key to songs table
 * @property float|null  $danceability      How suitable for dancing (0.0–1.0)
 * @property float|null  $energy            Perceptual intensity (0.0–1.0)
 * @property float|null  $valence           Musical positivity (0.0–1.0)
 * @property float|null  $acousticness      Acoustic vs. electronic (0.0–1.0)
 * @property float|null  $instrumentalness  Vocal vs. instrumental (0.0–1.0)
 * @property float|null  $tempo             Estimated BPM
 * @property float|null  $speechiness       Presence of spoken words (0.0–1.0)
 * @property float|null  $liveness          Audience presence likelihood (0.0–1.0)
 * @property float|null  $loudness          Overall loudness in dB
 * @property int|null    $key               Musical key (0=C, 1=C#, ..., 11=B)
 * @property int|null    $mode              Major (1) or minor (0)
 * @property int|null    $time_signature    Beats per measure
 * @property string|null $description       AI-generated natural-language description
 */
class SongFeature extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'song_id',
        'danceability',
        'energy',
        'valence',
        'acousticness',
        'instrumentalness',
        'tempo',
        'speechiness',
        'liveness',
        'loudness',
        'key',
        'mode',
        'time_signature',
        'description',
    ];

    /**
     * Get the song that this feature record belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function song()
    {
        return $this->belongsTo(Song::class);
    }
}